=== Justasic/cia-vc/xml/schema.xsd
<?xml version="1.0"?>
<xsd:schema
 xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:complexType name="fileList">
  <xsd:choice maxOccurs="unbounded">
    <xsd:element name="file" type="xsd:string"/>
  </xsd:choice>
</xsd:complexType>

<xsd:complexType name="commit">
  <xsd:choice maxOccurs="unbounded">
    <xsd:element name="revision" type="xsd:string"/>
    <xsd:element name="log" type="xsd:string"/>
    <xsd:element name="files" type="fileList"/>
  </xsd:choice>
</xsd:complexType>

<xsd:complexType name="message-body">
  <xsd:choice>
    <xsd:element name="commit" type="commit"/>
  </xsd:choice>
</xsd:complexType>

<xsd:complexType name="message-source">
  <xsd:choice maxOccurs="unbounded">
    <xsd:element name="project" type="xsd:string"/>
    <xsd:element name="module" type="xsd:string"/>
    <xsd:element name="branch" type="xsd:string"/>
  </xsd:choice>
</xsd:complexType>

<xsd:complexType name="message-generator">
  <xsd:choice maxOccurs="unbounded">
    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="version" type="xsd:decimal"/>
    <xsd:element name="url" type="xsd:string"/>
  </xsd:choice>
</xsd:complexType>

<xsd:element name="message">
  <xsd:complexType>
    <xsd:choice maxOccurs="unbounded" minOccurs="0">
      <xsd:element name="generator" type="message-generator"/>
      <xsd:element name="source" type="message-source"/>
      <xsd:element name="timestamp" type="xsd:integer"/>
      <xsd:element name="body" type="message-body"/>
    </xsd:choice>
  </xsd:complexType>
</xsd:element>

</xsd:schema>

=== Justasic/cia-vc/xml/samples/simple-message.xml
<message
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
   <generator>
       <name>CIA client for Subversion</name>
       <version>0.52</version>
       <url>http://navi/foo</url>
   </generator>
   <source>
       <project>navi-misc</project>
       <module>cia</module>
       <branch>trunk</branch>
   </source>
   <timestamp>
       1071372095
   </timestamp>
   <body>
       <commit>
	   <revision>1132</revision>
           <author>Professor Wigglepuppy</author>
	   <files>
	       <file>trunk/cia/LibCIA/Message.py</file>
	       <file>trunk/cia/LibCIA/IRC.py</file>
	   </files>
	   <log>
	       Another commit.. the whole log message would
	       go here, and it's up to message formatters to
	       choose how much to display
	   </log>
       </commit>
   </body>
</message>
